// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package minGamePb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//防沉迷状态
type FcmState int32

const (
	//成功
	FcmState_Success FcmState = 0
	//认证失败
	FcmState_Fail FcmState = 1
	//未成年,该时间段不能玩游戏
	FcmState_Monage FcmState = 2
)

var FcmState_name = map[int32]string{
	0: "Success",
	1: "Fail",
	2: "Monage",
}

var FcmState_value = map[string]int32{
	"Success": 0,
	"Fail":    1,
	"Monage":  2,
}

func (x FcmState) Enum() *FcmState {
	p := new(FcmState)
	*p = x
	return p
}

func (x FcmState) String() string {
	return proto.EnumName(FcmState_name, int32(x))
}

func (x *FcmState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FcmState_value, data, "FcmState")
	if err != nil {
		return err
	}
	*x = FcmState(value)
	return nil
}

func (FcmState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

// 微信登录数据
type WxLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Encrypteddata        *string  `protobuf:"bytes,2,opt,name=encrypteddata" json:"encrypteddata,omitempty"`
	Iv                   *string  `protobuf:"bytes,3,opt,name=iv" json:"iv,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	Inviter              *int64   `protobuf:"varint,6,opt,name=inviter" json:"inviter,omitempty"`
	Addr                 *string  `protobuf:"bytes,7,opt,name=addr" json:"addr,omitempty"`
	Openid               *string  `protobuf:"bytes,8,opt,name=openid" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxLoginData) Reset()         { *m = WxLoginData{} }
func (m *WxLoginData) String() string { return proto.CompactTextString(m) }
func (*WxLoginData) ProtoMessage()    {}
func (*WxLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *WxLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxLoginData.Unmarshal(m, b)
}
func (m *WxLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxLoginData.Marshal(b, m, deterministic)
}
func (m *WxLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxLoginData.Merge(m, src)
}
func (m *WxLoginData) XXX_Size() int {
	return xxx_messageInfo_WxLoginData.Size(m)
}
func (m *WxLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_WxLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_WxLoginData proto.InternalMessageInfo

func (m *WxLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *WxLoginData) GetEncrypteddata() string {
	if m != nil && m.Encrypteddata != nil {
		return *m.Encrypteddata
	}
	return ""
}

func (m *WxLoginData) GetIv() string {
	if m != nil && m.Iv != nil {
		return *m.Iv
	}
	return ""
}

func (m *WxLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *WxLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *WxLoginData) GetInviter() int64 {
	if m != nil && m.Inviter != nil {
		return *m.Inviter
	}
	return 0
}

func (m *WxLoginData) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *WxLoginData) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

// 玩吧登录数据
type WanBaLoginData struct {
	Openid               *string  `protobuf:"bytes,1,opt,name=openid" json:"openid,omitempty"`
	Openkey              *string  `protobuf:"bytes,2,opt,name=openkey" json:"openkey,omitempty"`
	Platform             *string  `protobuf:"bytes,3,opt,name=platform" json:"platform,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	Addr                 *string  `protobuf:"bytes,6,opt,name=addr" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WanBaLoginData) Reset()         { *m = WanBaLoginData{} }
func (m *WanBaLoginData) String() string { return proto.CompactTextString(m) }
func (*WanBaLoginData) ProtoMessage()    {}
func (*WanBaLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *WanBaLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WanBaLoginData.Unmarshal(m, b)
}
func (m *WanBaLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WanBaLoginData.Marshal(b, m, deterministic)
}
func (m *WanBaLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WanBaLoginData.Merge(m, src)
}
func (m *WanBaLoginData) XXX_Size() int {
	return xxx_messageInfo_WanBaLoginData.Size(m)
}
func (m *WanBaLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_WanBaLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_WanBaLoginData proto.InternalMessageInfo

func (m *WanBaLoginData) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

func (m *WanBaLoginData) GetOpenkey() string {
	if m != nil && m.Openkey != nil {
		return *m.Openkey
	}
	return ""
}

func (m *WanBaLoginData) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *WanBaLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *WanBaLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *WanBaLoginData) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

// ToutiaoLoginData 头条登录数据
type ToutiaoLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Encrypteddata        *string  `protobuf:"bytes,2,opt,name=encrypteddata" json:"encrypteddata,omitempty"`
	Iv                   *string  `protobuf:"bytes,3,opt,name=iv" json:"iv,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	AnonymousCode        *string  `protobuf:"bytes,6,opt,name=anonymous_code,json=anonymousCode" json:"anonymous_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToutiaoLoginData) Reset()         { *m = ToutiaoLoginData{} }
func (m *ToutiaoLoginData) String() string { return proto.CompactTextString(m) }
func (*ToutiaoLoginData) ProtoMessage()    {}
func (*ToutiaoLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *ToutiaoLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToutiaoLoginData.Unmarshal(m, b)
}
func (m *ToutiaoLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToutiaoLoginData.Marshal(b, m, deterministic)
}
func (m *ToutiaoLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToutiaoLoginData.Merge(m, src)
}
func (m *ToutiaoLoginData) XXX_Size() int {
	return xxx_messageInfo_ToutiaoLoginData.Size(m)
}
func (m *ToutiaoLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_ToutiaoLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_ToutiaoLoginData proto.InternalMessageInfo

func (m *ToutiaoLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *ToutiaoLoginData) GetEncrypteddata() string {
	if m != nil && m.Encrypteddata != nil {
		return *m.Encrypteddata
	}
	return ""
}

func (m *ToutiaoLoginData) GetIv() string {
	if m != nil && m.Iv != nil {
		return *m.Iv
	}
	return ""
}

func (m *ToutiaoLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *ToutiaoLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *ToutiaoLoginData) GetAnonymousCode() string {
	if m != nil && m.AnonymousCode != nil {
		return *m.AnonymousCode
	}
	return ""
}

// YiJieLoginData 易接登录数据
type YiJieLoginData struct {
	Sdk                  *string  `protobuf:"bytes,1,opt,name=sdk" json:"sdk,omitempty"`
	App                  *string  `protobuf:"bytes,2,opt,name=app" json:"app,omitempty"`
	Uin                  *string  `protobuf:"bytes,3,opt,name=uin" json:"uin,omitempty"`
	Sess                 *string  `protobuf:"bytes,4,opt,name=sess" json:"sess,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,5,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,6,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YiJieLoginData) Reset()         { *m = YiJieLoginData{} }
func (m *YiJieLoginData) String() string { return proto.CompactTextString(m) }
func (*YiJieLoginData) ProtoMessage()    {}
func (*YiJieLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *YiJieLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YiJieLoginData.Unmarshal(m, b)
}
func (m *YiJieLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YiJieLoginData.Marshal(b, m, deterministic)
}
func (m *YiJieLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YiJieLoginData.Merge(m, src)
}
func (m *YiJieLoginData) XXX_Size() int {
	return xxx_messageInfo_YiJieLoginData.Size(m)
}
func (m *YiJieLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_YiJieLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_YiJieLoginData proto.InternalMessageInfo

func (m *YiJieLoginData) GetSdk() string {
	if m != nil && m.Sdk != nil {
		return *m.Sdk
	}
	return ""
}

func (m *YiJieLoginData) GetApp() string {
	if m != nil && m.App != nil {
		return *m.App
	}
	return ""
}

func (m *YiJieLoginData) GetUin() string {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return ""
}

func (m *YiJieLoginData) GetSess() string {
	if m != nil && m.Sess != nil {
		return *m.Sess
	}
	return ""
}

func (m *YiJieLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *YiJieLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

//  YiJieDanJiLoginData 易接单机登录数据
type YiJieDanJiLoginData struct {
	DeviceId             *string  `protobuf:"bytes,1,opt,name=deviceId" json:"deviceId,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	Inviter              *int64   `protobuf:"varint,6,opt,name=inviter" json:"inviter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YiJieDanJiLoginData) Reset()         { *m = YiJieDanJiLoginData{} }
func (m *YiJieDanJiLoginData) String() string { return proto.CompactTextString(m) }
func (*YiJieDanJiLoginData) ProtoMessage()    {}
func (*YiJieDanJiLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *YiJieDanJiLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YiJieDanJiLoginData.Unmarshal(m, b)
}
func (m *YiJieDanJiLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YiJieDanJiLoginData.Marshal(b, m, deterministic)
}
func (m *YiJieDanJiLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YiJieDanJiLoginData.Merge(m, src)
}
func (m *YiJieDanJiLoginData) XXX_Size() int {
	return xxx_messageInfo_YiJieDanJiLoginData.Size(m)
}
func (m *YiJieDanJiLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_YiJieDanJiLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_YiJieDanJiLoginData proto.InternalMessageInfo

func (m *YiJieDanJiLoginData) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *YiJieDanJiLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *YiJieDanJiLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *YiJieDanJiLoginData) GetInviter() int64 {
	if m != nil && m.Inviter != nil {
		return *m.Inviter
	}
	return 0
}

// QQLoginData QQ登录数据
type QQLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Encrypteddata        *string  `protobuf:"bytes,2,opt,name=encrypteddata" json:"encrypteddata,omitempty"`
	Iv                   *string  `protobuf:"bytes,3,opt,name=iv" json:"iv,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	Openid               *string  `protobuf:"bytes,6,opt,name=openid" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QQLoginData) Reset()         { *m = QQLoginData{} }
func (m *QQLoginData) String() string { return proto.CompactTextString(m) }
func (*QQLoginData) ProtoMessage()    {}
func (*QQLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *QQLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QQLoginData.Unmarshal(m, b)
}
func (m *QQLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QQLoginData.Marshal(b, m, deterministic)
}
func (m *QQLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QQLoginData.Merge(m, src)
}
func (m *QQLoginData) XXX_Size() int {
	return xxx_messageInfo_QQLoginData.Size(m)
}
func (m *QQLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_QQLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_QQLoginData proto.InternalMessageInfo

func (m *QQLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *QQLoginData) GetEncrypteddata() string {
	if m != nil && m.Encrypteddata != nil {
		return *m.Encrypteddata
	}
	return ""
}

func (m *QQLoginData) GetIv() string {
	if m != nil && m.Iv != nil {
		return *m.Iv
	}
	return ""
}

func (m *QQLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *QQLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *QQLoginData) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

// BilibiliLoginData b站登录数据
type BilibiliLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Encrypteddata        *string  `protobuf:"bytes,2,opt,name=encrypteddata" json:"encrypteddata,omitempty"`
	Iv                   *string  `protobuf:"bytes,3,opt,name=iv" json:"iv,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BilibiliLoginData) Reset()         { *m = BilibiliLoginData{} }
func (m *BilibiliLoginData) String() string { return proto.CompactTextString(m) }
func (*BilibiliLoginData) ProtoMessage()    {}
func (*BilibiliLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *BilibiliLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BilibiliLoginData.Unmarshal(m, b)
}
func (m *BilibiliLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BilibiliLoginData.Marshal(b, m, deterministic)
}
func (m *BilibiliLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BilibiliLoginData.Merge(m, src)
}
func (m *BilibiliLoginData) XXX_Size() int {
	return xxx_messageInfo_BilibiliLoginData.Size(m)
}
func (m *BilibiliLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_BilibiliLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_BilibiliLoginData proto.InternalMessageInfo

func (m *BilibiliLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *BilibiliLoginData) GetEncrypteddata() string {
	if m != nil && m.Encrypteddata != nil {
		return *m.Encrypteddata
	}
	return ""
}

func (m *BilibiliLoginData) GetIv() string {
	if m != nil && m.Iv != nil {
		return *m.Iv
	}
	return ""
}

func (m *BilibiliLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *BilibiliLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

// PasswordData 账号密码登录
type PasswordData struct {
	Userid               *string  `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordData) Reset()         { *m = PasswordData{} }
func (m *PasswordData) String() string { return proto.CompactTextString(m) }
func (*PasswordData) ProtoMessage()    {}
func (*PasswordData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *PasswordData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordData.Unmarshal(m, b)
}
func (m *PasswordData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordData.Marshal(b, m, deterministic)
}
func (m *PasswordData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordData.Merge(m, src)
}
func (m *PasswordData) XXX_Size() int {
	return xxx_messageInfo_PasswordData.Size(m)
}
func (m *PasswordData) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordData.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordData proto.InternalMessageInfo

func (m *PasswordData) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *PasswordData) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// OPPOLoginData oppo登录数据
type OPPOLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	PkgName              *string  `protobuf:"bytes,2,opt,name=pkgName" json:"pkgName,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,3,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,4,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OPPOLoginData) Reset()         { *m = OPPOLoginData{} }
func (m *OPPOLoginData) String() string { return proto.CompactTextString(m) }
func (*OPPOLoginData) ProtoMessage()    {}
func (*OPPOLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *OPPOLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OPPOLoginData.Unmarshal(m, b)
}
func (m *OPPOLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OPPOLoginData.Marshal(b, m, deterministic)
}
func (m *OPPOLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OPPOLoginData.Merge(m, src)
}
func (m *OPPOLoginData) XXX_Size() int {
	return xxx_messageInfo_OPPOLoginData.Size(m)
}
func (m *OPPOLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_OPPOLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_OPPOLoginData proto.InternalMessageInfo

func (m *OPPOLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *OPPOLoginData) GetPkgName() string {
	if m != nil && m.PkgName != nil {
		return *m.PkgName
	}
	return ""
}

func (m *OPPOLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *OPPOLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

// HuaweiLoginData 华为登录数据
type HuaweiLoginData struct {
	Ts                   *string  `protobuf:"bytes,1,opt,name=ts" json:"ts,omitempty"`
	Playerid             *string  `protobuf:"bytes,2,opt,name=playerid" json:"playerid,omitempty"`
	Playerlevel          *string  `protobuf:"bytes,3,opt,name=playerlevel" json:"playerlevel,omitempty"`
	Playersign           *string  `protobuf:"bytes,4,opt,name=playersign" json:"playersign,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,5,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,6,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HuaweiLoginData) Reset()         { *m = HuaweiLoginData{} }
func (m *HuaweiLoginData) String() string { return proto.CompactTextString(m) }
func (*HuaweiLoginData) ProtoMessage()    {}
func (*HuaweiLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *HuaweiLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuaweiLoginData.Unmarshal(m, b)
}
func (m *HuaweiLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuaweiLoginData.Marshal(b, m, deterministic)
}
func (m *HuaweiLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuaweiLoginData.Merge(m, src)
}
func (m *HuaweiLoginData) XXX_Size() int {
	return xxx_messageInfo_HuaweiLoginData.Size(m)
}
func (m *HuaweiLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_HuaweiLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_HuaweiLoginData proto.InternalMessageInfo

func (m *HuaweiLoginData) GetTs() string {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return ""
}

func (m *HuaweiLoginData) GetPlayerid() string {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return ""
}

func (m *HuaweiLoginData) GetPlayerlevel() string {
	if m != nil && m.Playerlevel != nil {
		return *m.Playerlevel
	}
	return ""
}

func (m *HuaweiLoginData) GetPlayersign() string {
	if m != nil && m.Playersign != nil {
		return *m.Playersign
	}
	return ""
}

func (m *HuaweiLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *HuaweiLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

// BingChuanLoginData 冰川登录数据
type BingChuanLoginData struct {
	Session              *string  `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,2,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,3,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BingChuanLoginData) Reset()         { *m = BingChuanLoginData{} }
func (m *BingChuanLoginData) String() string { return proto.CompactTextString(m) }
func (*BingChuanLoginData) ProtoMessage()    {}
func (*BingChuanLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *BingChuanLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BingChuanLoginData.Unmarshal(m, b)
}
func (m *BingChuanLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BingChuanLoginData.Marshal(b, m, deterministic)
}
func (m *BingChuanLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BingChuanLoginData.Merge(m, src)
}
func (m *BingChuanLoginData) XXX_Size() int {
	return xxx_messageInfo_BingChuanLoginData.Size(m)
}
func (m *BingChuanLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_BingChuanLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_BingChuanLoginData proto.InternalMessageInfo

func (m *BingChuanLoginData) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

func (m *BingChuanLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *BingChuanLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

// PhoneLoginData 手机登录数据
type PhoneLoginData struct {
	Phoneno              *string  `protobuf:"bytes,1,opt,name=phoneno" json:"phoneno,omitempty"`
	Phonecode            *string  `protobuf:"bytes,2,opt,name=phonecode" json:"phonecode,omitempty"`
	Password             *string  `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneLoginData) Reset()         { *m = PhoneLoginData{} }
func (m *PhoneLoginData) String() string { return proto.CompactTextString(m) }
func (*PhoneLoginData) ProtoMessage()    {}
func (*PhoneLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *PhoneLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneLoginData.Unmarshal(m, b)
}
func (m *PhoneLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneLoginData.Marshal(b, m, deterministic)
}
func (m *PhoneLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneLoginData.Merge(m, src)
}
func (m *PhoneLoginData) XXX_Size() int {
	return xxx_messageInfo_PhoneLoginData.Size(m)
}
func (m *PhoneLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneLoginData proto.InternalMessageInfo

func (m *PhoneLoginData) GetPhoneno() string {
	if m != nil && m.Phoneno != nil {
		return *m.Phoneno
	}
	return ""
}

func (m *PhoneLoginData) GetPhonecode() string {
	if m != nil && m.Phonecode != nil {
		return *m.Phonecode
	}
	return ""
}

func (m *PhoneLoginData) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// BasicData 基础数据
type BasicData struct {
	SubChannel           *string  `protobuf:"bytes,1,opt,name=subChannel" json:"subChannel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicData) Reset()         { *m = BasicData{} }
func (m *BasicData) String() string { return proto.CompactTextString(m) }
func (*BasicData) ProtoMessage()    {}
func (*BasicData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *BasicData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicData.Unmarshal(m, b)
}
func (m *BasicData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicData.Marshal(b, m, deterministic)
}
func (m *BasicData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicData.Merge(m, src)
}
func (m *BasicData) XXX_Size() int {
	return xxx_messageInfo_BasicData.Size(m)
}
func (m *BasicData) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicData.DiscardUnknown(m)
}

var xxx_messageInfo_BasicData proto.InternalMessageInfo

func (m *BasicData) GetSubChannel() string {
	if m != nil && m.SubChannel != nil {
		return *m.SubChannel
	}
	return ""
}

// 账号认证请求
type AuthReq struct {
	GameId               *GameId              `protobuf:"varint,1,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	WxData               *WxLoginData         `protobuf:"bytes,2,opt,name=wxData" json:"wxData,omitempty"`
	WanbaData            *WanBaLoginData      `protobuf:"bytes,3,opt,name=wanbaData" json:"wanbaData,omitempty"`
	ToutiaoData          *ToutiaoLoginData    `protobuf:"bytes,4,opt,name=toutiaoData" json:"toutiaoData,omitempty"`
	Nick                 *string              `protobuf:"bytes,5,opt,name=nick" json:"nick,omitempty"`
	Sex                  *int32               `protobuf:"varint,6,opt,name=sex" json:"sex,omitempty"`
	AvatarUrl            *string              `protobuf:"bytes,7,opt,name=avatarUrl" json:"avatarUrl,omitempty"`
	YijiData             *YiJieLoginData      `protobuf:"bytes,8,opt,name=yijiData" json:"yijiData,omitempty"`
	QQData               *QQLoginData         `protobuf:"bytes,9,opt,name=QQData" json:"QQData,omitempty"`
	BbData               *BilibiliLoginData   `protobuf:"bytes,10,opt,name=bbData" json:"bbData,omitempty"`
	YijiedanjiData       *YiJieDanJiLoginData `protobuf:"bytes,11,opt,name=yijiedanjiData" json:"yijiedanjiData,omitempty"`
	OppoData             *OPPOLoginData       `protobuf:"bytes,12,opt,name=oppoData" json:"oppoData,omitempty"`
	PasswordData         *PasswordData        `protobuf:"bytes,13,opt,name=passwordData" json:"passwordData,omitempty"`
	PhoneData            *PhoneLoginData      `protobuf:"bytes,14,opt,name=phoneData" json:"phoneData,omitempty"`
	BasicData            *BasicData           `protobuf:"bytes,15,opt,name=basicData" json:"basicData,omitempty"`
	HuaweiData           *HuaweiLoginData     `protobuf:"bytes,16,opt,name=huaweiData" json:"huaweiData,omitempty"`
	BingchuanData        *BingChuanLoginData  `protobuf:"bytes,17,opt,name=bingchuanData" json:"bingchuanData,omitempty"`
	QQBindData           *QQBindLoginData     `protobuf:"bytes,18,opt,name=QQBindData" json:"QQBindData,omitempty"`
	Xcwl                 *XCLoginData         `protobuf:"bytes,19,opt,name=xcwl" json:"xcwl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *AuthReq) GetWxData() *WxLoginData {
	if m != nil {
		return m.WxData
	}
	return nil
}

func (m *AuthReq) GetWanbaData() *WanBaLoginData {
	if m != nil {
		return m.WanbaData
	}
	return nil
}

func (m *AuthReq) GetToutiaoData() *ToutiaoLoginData {
	if m != nil {
		return m.ToutiaoData
	}
	return nil
}

func (m *AuthReq) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *AuthReq) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *AuthReq) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *AuthReq) GetYijiData() *YiJieLoginData {
	if m != nil {
		return m.YijiData
	}
	return nil
}

func (m *AuthReq) GetQQData() *QQLoginData {
	if m != nil {
		return m.QQData
	}
	return nil
}

func (m *AuthReq) GetBbData() *BilibiliLoginData {
	if m != nil {
		return m.BbData
	}
	return nil
}

func (m *AuthReq) GetYijiedanjiData() *YiJieDanJiLoginData {
	if m != nil {
		return m.YijiedanjiData
	}
	return nil
}

func (m *AuthReq) GetOppoData() *OPPOLoginData {
	if m != nil {
		return m.OppoData
	}
	return nil
}

func (m *AuthReq) GetPasswordData() *PasswordData {
	if m != nil {
		return m.PasswordData
	}
	return nil
}

func (m *AuthReq) GetPhoneData() *PhoneLoginData {
	if m != nil {
		return m.PhoneData
	}
	return nil
}

func (m *AuthReq) GetBasicData() *BasicData {
	if m != nil {
		return m.BasicData
	}
	return nil
}

func (m *AuthReq) GetHuaweiData() *HuaweiLoginData {
	if m != nil {
		return m.HuaweiData
	}
	return nil
}

func (m *AuthReq) GetBingchuanData() *BingChuanLoginData {
	if m != nil {
		return m.BingchuanData
	}
	return nil
}

func (m *AuthReq) GetQQBindData() *QQBindLoginData {
	if m != nil {
		return m.QQBindData
	}
	return nil
}

func (m *AuthReq) GetXcwl() *XCLoginData {
	if m != nil {
		return m.Xcwl
	}
	return nil
}

// 防沉迷
type FcmInfo struct {
	State                *FcmState `protobuf:"varint,1,opt,name=state,enum=minGamePb.FcmState" json:"state,omitempty"`
	EnforceLogoutTime    *int64    `protobuf:"varint,2,opt,name=enforceLogoutTime" json:"enforceLogoutTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FcmInfo) Reset()         { *m = FcmInfo{} }
func (m *FcmInfo) String() string { return proto.CompactTextString(m) }
func (*FcmInfo) ProtoMessage()    {}
func (*FcmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *FcmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FcmInfo.Unmarshal(m, b)
}
func (m *FcmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FcmInfo.Marshal(b, m, deterministic)
}
func (m *FcmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FcmInfo.Merge(m, src)
}
func (m *FcmInfo) XXX_Size() int {
	return xxx_messageInfo_FcmInfo.Size(m)
}
func (m *FcmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FcmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FcmInfo proto.InternalMessageInfo

func (m *FcmInfo) GetState() FcmState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return FcmState_Success
}

func (m *FcmInfo) GetEnforceLogoutTime() int64 {
	if m != nil && m.EnforceLogoutTime != nil {
		return *m.EnforceLogoutTime
	}
	return 0
}

// 账号认证响应
type AuthRsp struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Openid               *string  `protobuf:"bytes,2,opt,name=openid" json:"openid,omitempty"`
	Account              []byte   `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	HasBind              *bool    `protobuf:"varint,4,opt,name=hasBind" json:"hasBind,omitempty"`
	Fcm                  *FcmInfo `protobuf:"bytes,5,opt,name=fcm" json:"fcm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRsp) Reset()         { *m = AuthRsp{} }
func (m *AuthRsp) String() string { return proto.CompactTextString(m) }
func (*AuthRsp) ProtoMessage()    {}
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *AuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRsp.Unmarshal(m, b)
}
func (m *AuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRsp.Marshal(b, m, deterministic)
}
func (m *AuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRsp.Merge(m, src)
}
func (m *AuthRsp) XXX_Size() int {
	return xxx_messageInfo_AuthRsp.Size(m)
}
func (m *AuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRsp proto.InternalMessageInfo

func (m *AuthRsp) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *AuthRsp) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

func (m *AuthRsp) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AuthRsp) GetHasBind() bool {
	if m != nil && m.HasBind != nil {
		return *m.HasBind
	}
	return false
}

func (m *AuthRsp) GetFcm() *FcmInfo {
	if m != nil {
		return m.Fcm
	}
	return nil
}

// 账号验证请求
type VerifyReq struct {
	CheckCode            *string  `protobuf:"bytes,1,opt,name=checkCode" json:"checkCode,omitempty"`
	Server               *string  `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	GameId               *GameId  `protobuf:"varint,3,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	Version              *string  `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetCheckCode() string {
	if m != nil && m.CheckCode != nil {
		return *m.CheckCode
	}
	return ""
}

func (m *VerifyReq) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *VerifyReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *VerifyReq) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

// 账号验证响应
type VerifyRsp struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRsp) Reset()         { *m = VerifyRsp{} }
func (m *VerifyRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyRsp) ProtoMessage()    {}
func (*VerifyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{17}
}

func (m *VerifyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRsp.Unmarshal(m, b)
}
func (m *VerifyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRsp.Marshal(b, m, deterministic)
}
func (m *VerifyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRsp.Merge(m, src)
}
func (m *VerifyRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyRsp.Size(m)
}
func (m *VerifyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRsp proto.InternalMessageInfo

func (m *VerifyRsp) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountUser struct {
	Server               *string  `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	GameId               *GameId  `protobuf:"varint,2,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	Version              *string  `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	CreateTime           *int64   `protobuf:"varint,4,opt,name=createTime" json:"createTime,omitempty"`
	LastLoginTime        *int64   `protobuf:"varint,5,opt,name=lastLoginTime" json:"lastLoginTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountUser) Reset()         { *m = AccountUser{} }
func (m *AccountUser) String() string { return proto.CompactTextString(m) }
func (*AccountUser) ProtoMessage()    {}
func (*AccountUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{18}
}

func (m *AccountUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountUser.Unmarshal(m, b)
}
func (m *AccountUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountUser.Marshal(b, m, deterministic)
}
func (m *AccountUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountUser.Merge(m, src)
}
func (m *AccountUser) XXX_Size() int {
	return xxx_messageInfo_AccountUser.Size(m)
}
func (m *AccountUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountUser.DiscardUnknown(m)
}

var xxx_messageInfo_AccountUser proto.InternalMessageInfo

func (m *AccountUser) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *AccountUser) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *AccountUser) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *AccountUser) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *AccountUser) GetLastLoginTime() int64 {
	if m != nil && m.LastLoginTime != nil {
		return *m.LastLoginTime
	}
	return 0
}

// 账号游戏信息请求
type AccountGameInfoReq struct {
	AccountId            *int64   `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	GameId               *GameId  `protobuf:"varint,2,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	Server               *string  `protobuf:"bytes,3,opt,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountGameInfoReq) Reset()         { *m = AccountGameInfoReq{} }
func (m *AccountGameInfoReq) String() string { return proto.CompactTextString(m) }
func (*AccountGameInfoReq) ProtoMessage()    {}
func (*AccountGameInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{19}
}

func (m *AccountGameInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountGameInfoReq.Unmarshal(m, b)
}
func (m *AccountGameInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountGameInfoReq.Marshal(b, m, deterministic)
}
func (m *AccountGameInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountGameInfoReq.Merge(m, src)
}
func (m *AccountGameInfoReq) XXX_Size() int {
	return xxx_messageInfo_AccountGameInfoReq.Size(m)
}
func (m *AccountGameInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountGameInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccountGameInfoReq proto.InternalMessageInfo

func (m *AccountGameInfoReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *AccountGameInfoReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *AccountGameInfoReq) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

// 账号游戏信息响应
type AccountGameInfoRsp struct {
	User                 []*AccountUser `protobuf:"bytes,1,rep,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountGameInfoRsp) Reset()         { *m = AccountGameInfoRsp{} }
func (m *AccountGameInfoRsp) String() string { return proto.CompactTextString(m) }
func (*AccountGameInfoRsp) ProtoMessage()    {}
func (*AccountGameInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{20}
}

func (m *AccountGameInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountGameInfoRsp.Unmarshal(m, b)
}
func (m *AccountGameInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountGameInfoRsp.Marshal(b, m, deterministic)
}
func (m *AccountGameInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountGameInfoRsp.Merge(m, src)
}
func (m *AccountGameInfoRsp) XXX_Size() int {
	return xxx_messageInfo_AccountGameInfoRsp.Size(m)
}
func (m *AccountGameInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountGameInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountGameInfoRsp proto.InternalMessageInfo

func (m *AccountGameInfoRsp) GetUser() []*AccountUser {
	if m != nil {
		return m.User
	}
	return nil
}

// 用户信息请求
type GetUserInfoReq struct {
	UserId               *int64   `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{21}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

// 用户信息响应
type GetUserInfoRsp struct {
	User                 *AccountUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{22}
}

func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetUser() *AccountUser {
	if m != nil {
		return m.User
	}
	return nil
}

// 用户密码设置
type SetPasswordReq struct {
	UserId               *string  `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordReq) Reset()         { *m = SetPasswordReq{} }
func (m *SetPasswordReq) String() string { return proto.CompactTextString(m) }
func (*SetPasswordReq) ProtoMessage()    {}
func (*SetPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{23}
}

func (m *SetPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordReq.Unmarshal(m, b)
}
func (m *SetPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordReq.Marshal(b, m, deterministic)
}
func (m *SetPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordReq.Merge(m, src)
}
func (m *SetPasswordReq) XXX_Size() int {
	return xxx_messageInfo_SetPasswordReq.Size(m)
}
func (m *SetPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordReq proto.InternalMessageInfo

func (m *SetPasswordReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *SetPasswordReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 用户密码修改
type ModifyPasswordReq struct {
	GameId               *GameId  `protobuf:"varint,1,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	Phoneno              *string  `protobuf:"bytes,2,opt,name=phoneno" json:"phoneno,omitempty"`
	Phonecode            *string  `protobuf:"bytes,3,opt,name=phonecode" json:"phonecode,omitempty"`
	Password             *string  `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPasswordReq) Reset()         { *m = ModifyPasswordReq{} }
func (m *ModifyPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ModifyPasswordReq) ProtoMessage()    {}
func (*ModifyPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{24}
}

func (m *ModifyPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPasswordReq.Unmarshal(m, b)
}
func (m *ModifyPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPasswordReq.Marshal(b, m, deterministic)
}
func (m *ModifyPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPasswordReq.Merge(m, src)
}
func (m *ModifyPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ModifyPasswordReq.Size(m)
}
func (m *ModifyPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPasswordReq proto.InternalMessageInfo

func (m *ModifyPasswordReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *ModifyPasswordReq) GetPhoneno() string {
	if m != nil && m.Phoneno != nil {
		return *m.Phoneno
	}
	return ""
}

func (m *ModifyPasswordReq) GetPhonecode() string {
	if m != nil && m.Phonecode != nil {
		return *m.Phonecode
	}
	return ""
}

func (m *ModifyPasswordReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

// 账号服获取手机验证码请求(path:/account/phone/sendcode)
type GetPhoneCodeReq struct {
	Phoneno              *string  `protobuf:"bytes,1,req,name=phoneno" json:"phoneno,omitempty"`
	Gamename             *string  `protobuf:"bytes,2,req,name=gamename" json:"gamename,omitempty"`
	Type                 *int32   `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPhoneCodeReq) Reset()         { *m = GetPhoneCodeReq{} }
func (m *GetPhoneCodeReq) String() string { return proto.CompactTextString(m) }
func (*GetPhoneCodeReq) ProtoMessage()    {}
func (*GetPhoneCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{25}
}

func (m *GetPhoneCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneCodeReq.Unmarshal(m, b)
}
func (m *GetPhoneCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneCodeReq.Marshal(b, m, deterministic)
}
func (m *GetPhoneCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneCodeReq.Merge(m, src)
}
func (m *GetPhoneCodeReq) XXX_Size() int {
	return xxx_messageInfo_GetPhoneCodeReq.Size(m)
}
func (m *GetPhoneCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneCodeReq proto.InternalMessageInfo

func (m *GetPhoneCodeReq) GetPhoneno() string {
	if m != nil && m.Phoneno != nil {
		return *m.Phoneno
	}
	return ""
}

func (m *GetPhoneCodeReq) GetGamename() string {
	if m != nil && m.Gamename != nil {
		return *m.Gamename
	}
	return ""
}

func (m *GetPhoneCodeReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 账号服获取手机验证码响应
type GetPhoneCodeRsp struct {
	Remaintime           *int32   `protobuf:"varint,1,req,name=remaintime" json:"remaintime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPhoneCodeRsp) Reset()         { *m = GetPhoneCodeRsp{} }
func (m *GetPhoneCodeRsp) String() string { return proto.CompactTextString(m) }
func (*GetPhoneCodeRsp) ProtoMessage()    {}
func (*GetPhoneCodeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{26}
}

func (m *GetPhoneCodeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneCodeRsp.Unmarshal(m, b)
}
func (m *GetPhoneCodeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneCodeRsp.Marshal(b, m, deterministic)
}
func (m *GetPhoneCodeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneCodeRsp.Merge(m, src)
}
func (m *GetPhoneCodeRsp) XXX_Size() int {
	return xxx_messageInfo_GetPhoneCodeRsp.Size(m)
}
func (m *GetPhoneCodeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneCodeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneCodeRsp proto.InternalMessageInfo

func (m *GetPhoneCodeRsp) GetRemaintime() int32 {
	if m != nil && m.Remaintime != nil {
		return *m.Remaintime
	}
	return 0
}

// 微信解绑请求
type WechatUnbindReq struct {
	GameId               *GameId  `protobuf:"varint,1,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	AccountId            *int32   `protobuf:"varint,2,req,name=accountId" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatUnbindReq) Reset()         { *m = WechatUnbindReq{} }
func (m *WechatUnbindReq) String() string { return proto.CompactTextString(m) }
func (*WechatUnbindReq) ProtoMessage()    {}
func (*WechatUnbindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{27}
}

func (m *WechatUnbindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatUnbindReq.Unmarshal(m, b)
}
func (m *WechatUnbindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatUnbindReq.Marshal(b, m, deterministic)
}
func (m *WechatUnbindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatUnbindReq.Merge(m, src)
}
func (m *WechatUnbindReq) XXX_Size() int {
	return xxx_messageInfo_WechatUnbindReq.Size(m)
}
func (m *WechatUnbindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatUnbindReq.DiscardUnknown(m)
}

var xxx_messageInfo_WechatUnbindReq proto.InternalMessageInfo

func (m *WechatUnbindReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

func (m *WechatUnbindReq) GetAccountId() int32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

// 设置账号信息请求
type SetAccounfoReq struct {
	AccountId            *int64   `protobuf:"varint,1,opt,name=accountId" json:"accountId,omitempty"`
	Cardcode             *string  `protobuf:"bytes,2,opt,name=cardcode" json:"cardcode,omitempty"`
	Cardname             *string  `protobuf:"bytes,3,opt,name=cardname" json:"cardname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAccounfoReq) Reset()         { *m = SetAccounfoReq{} }
func (m *SetAccounfoReq) String() string { return proto.CompactTextString(m) }
func (*SetAccounfoReq) ProtoMessage()    {}
func (*SetAccounfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{28}
}

func (m *SetAccounfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccounfoReq.Unmarshal(m, b)
}
func (m *SetAccounfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccounfoReq.Marshal(b, m, deterministic)
}
func (m *SetAccounfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccounfoReq.Merge(m, src)
}
func (m *SetAccounfoReq) XXX_Size() int {
	return xxx_messageInfo_SetAccounfoReq.Size(m)
}
func (m *SetAccounfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccounfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccounfoReq proto.InternalMessageInfo

func (m *SetAccounfoReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *SetAccounfoReq) GetCardcode() string {
	if m != nil && m.Cardcode != nil {
		return *m.Cardcode
	}
	return ""
}

func (m *SetAccounfoReq) GetCardname() string {
	if m != nil && m.Cardname != nil {
		return *m.Cardname
	}
	return ""
}

// 绑定第三方账号请求
type BindAccounPlatformReq struct {
	Type                 *int32           `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	AuthCode             *string          `protobuf:"bytes,2,opt,name=authCode" json:"authCode,omitempty"`
	QQBindData           *QQBindLoginData `protobuf:"bytes,3,opt,name=QQBindData" json:"QQBindData,omitempty"`
	GameId               *GameId          `protobuf:"varint,4,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BindAccounPlatformReq) Reset()         { *m = BindAccounPlatformReq{} }
func (m *BindAccounPlatformReq) String() string { return proto.CompactTextString(m) }
func (*BindAccounPlatformReq) ProtoMessage()    {}
func (*BindAccounPlatformReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{29}
}

func (m *BindAccounPlatformReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindAccounPlatformReq.Unmarshal(m, b)
}
func (m *BindAccounPlatformReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindAccounPlatformReq.Marshal(b, m, deterministic)
}
func (m *BindAccounPlatformReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindAccounPlatformReq.Merge(m, src)
}
func (m *BindAccounPlatformReq) XXX_Size() int {
	return xxx_messageInfo_BindAccounPlatformReq.Size(m)
}
func (m *BindAccounPlatformReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindAccounPlatformReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindAccounPlatformReq proto.InternalMessageInfo

func (m *BindAccounPlatformReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BindAccounPlatformReq) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *BindAccounPlatformReq) GetQQBindData() *QQBindLoginData {
	if m != nil {
		return m.QQBindData
	}
	return nil
}

func (m *BindAccounPlatformReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

// 绑定WX账号请求
type BindAccounWxPlatformReq struct {
	Type                 *int32       `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	AuthCode             *string      `protobuf:"bytes,2,opt,name=authCode" json:"authCode,omitempty"`
	WxData               *WxLoginData `protobuf:"bytes,3,opt,name=wxData" json:"wxData,omitempty"`
	GameId               *GameId      `protobuf:"varint,4,opt,name=gameId,enum=minGamePb.GameId" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BindAccounWxPlatformReq) Reset()         { *m = BindAccounWxPlatformReq{} }
func (m *BindAccounWxPlatformReq) String() string { return proto.CompactTextString(m) }
func (*BindAccounWxPlatformReq) ProtoMessage()    {}
func (*BindAccounWxPlatformReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{30}
}

func (m *BindAccounWxPlatformReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindAccounWxPlatformReq.Unmarshal(m, b)
}
func (m *BindAccounWxPlatformReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindAccounWxPlatformReq.Marshal(b, m, deterministic)
}
func (m *BindAccounWxPlatformReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindAccounWxPlatformReq.Merge(m, src)
}
func (m *BindAccounWxPlatformReq) XXX_Size() int {
	return xxx_messageInfo_BindAccounWxPlatformReq.Size(m)
}
func (m *BindAccounWxPlatformReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindAccounWxPlatformReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindAccounWxPlatformReq proto.InternalMessageInfo

func (m *BindAccounWxPlatformReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *BindAccounWxPlatformReq) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *BindAccounWxPlatformReq) GetWxData() *WxLoginData {
	if m != nil {
		return m.WxData
	}
	return nil
}

func (m *BindAccounWxPlatformReq) GetGameId() GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return GameId_BattlePlatform
}

// QQBindLoginData QQ登录数据
type QQBindLoginData struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Encrypteddata        *string  `protobuf:"bytes,2,opt,name=encrypteddata" json:"encrypteddata,omitempty"`
	Iv                   *string  `protobuf:"bytes,3,opt,name=iv" json:"iv,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,4,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,5,opt,name=subplateform" json:"subplateform,omitempty"`
	Openid               *string  `protobuf:"bytes,6,opt,name=openid" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QQBindLoginData) Reset()         { *m = QQBindLoginData{} }
func (m *QQBindLoginData) String() string { return proto.CompactTextString(m) }
func (*QQBindLoginData) ProtoMessage()    {}
func (*QQBindLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{31}
}

func (m *QQBindLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QQBindLoginData.Unmarshal(m, b)
}
func (m *QQBindLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QQBindLoginData.Marshal(b, m, deterministic)
}
func (m *QQBindLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QQBindLoginData.Merge(m, src)
}
func (m *QQBindLoginData) XXX_Size() int {
	return xxx_messageInfo_QQBindLoginData.Size(m)
}
func (m *QQBindLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_QQBindLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_QQBindLoginData proto.InternalMessageInfo

func (m *QQBindLoginData) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *QQBindLoginData) GetEncrypteddata() string {
	if m != nil && m.Encrypteddata != nil {
		return *m.Encrypteddata
	}
	return ""
}

func (m *QQBindLoginData) GetIv() string {
	if m != nil && m.Iv != nil {
		return *m.Iv
	}
	return ""
}

func (m *QQBindLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *QQBindLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

func (m *QQBindLoginData) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

//XCLoginData星辰网络登陆数据
type XCLoginData struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Uid                  *string  `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Mainplatform         *string  `protobuf:"bytes,3,opt,name=mainplatform" json:"mainplatform,omitempty"`
	Subplateform         *string  `protobuf:"bytes,4,opt,name=subplateform" json:"subplateform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XCLoginData) Reset()         { *m = XCLoginData{} }
func (m *XCLoginData) String() string { return proto.CompactTextString(m) }
func (*XCLoginData) ProtoMessage()    {}
func (*XCLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{32}
}

func (m *XCLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XCLoginData.Unmarshal(m, b)
}
func (m *XCLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XCLoginData.Marshal(b, m, deterministic)
}
func (m *XCLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XCLoginData.Merge(m, src)
}
func (m *XCLoginData) XXX_Size() int {
	return xxx_messageInfo_XCLoginData.Size(m)
}
func (m *XCLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_XCLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_XCLoginData proto.InternalMessageInfo

func (m *XCLoginData) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *XCLoginData) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *XCLoginData) GetMainplatform() string {
	if m != nil && m.Mainplatform != nil {
		return *m.Mainplatform
	}
	return ""
}

func (m *XCLoginData) GetSubplateform() string {
	if m != nil && m.Subplateform != nil {
		return *m.Subplateform
	}
	return ""
}

// 获取绑定QQ号验证请求
type GetBindQQReq struct {
	Code                 *string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBindQQReq) Reset()         { *m = GetBindQQReq{} }
func (m *GetBindQQReq) String() string { return proto.CompactTextString(m) }
func (*GetBindQQReq) ProtoMessage()    {}
func (*GetBindQQReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{33}
}

func (m *GetBindQQReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBindQQReq.Unmarshal(m, b)
}
func (m *GetBindQQReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBindQQReq.Marshal(b, m, deterministic)
}
func (m *GetBindQQReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBindQQReq.Merge(m, src)
}
func (m *GetBindQQReq) XXX_Size() int {
	return xxx_messageInfo_GetBindQQReq.Size(m)
}
func (m *GetBindQQReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBindQQReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBindQQReq proto.InternalMessageInfo

func (m *GetBindQQReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// 获取绑定QQ号验证响应
type GetBindQQRsp struct {
	Qq                   *string  `protobuf:"bytes,1,opt,name=qq" json:"qq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBindQQRsp) Reset()         { *m = GetBindQQRsp{} }
func (m *GetBindQQRsp) String() string { return proto.CompactTextString(m) }
func (*GetBindQQRsp) ProtoMessage()    {}
func (*GetBindQQRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{34}
}

func (m *GetBindQQRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBindQQRsp.Unmarshal(m, b)
}
func (m *GetBindQQRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBindQQRsp.Marshal(b, m, deterministic)
}
func (m *GetBindQQRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBindQQRsp.Merge(m, src)
}
func (m *GetBindQQRsp) XXX_Size() int {
	return xxx_messageInfo_GetBindQQRsp.Size(m)
}
func (m *GetBindQQRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBindQQRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBindQQRsp proto.InternalMessageInfo

func (m *GetBindQQRsp) GetQq() string {
	if m != nil && m.Qq != nil {
		return *m.Qq
	}
	return ""
}

// 绑定QQ账号请求
type BindAccounQQReq struct {
	AuthCode             *string  `protobuf:"bytes,1,opt,name=authCode" json:"authCode,omitempty"`
	Qq                   *string  `protobuf:"bytes,2,opt,name=qq" json:"qq,omitempty"`
	GameId               *int32   `protobuf:"varint,3,opt,name=gameId" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindAccounQQReq) Reset()         { *m = BindAccounQQReq{} }
func (m *BindAccounQQReq) String() string { return proto.CompactTextString(m) }
func (*BindAccounQQReq) ProtoMessage()    {}
func (*BindAccounQQReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{35}
}

func (m *BindAccounQQReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindAccounQQReq.Unmarshal(m, b)
}
func (m *BindAccounQQReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindAccounQQReq.Marshal(b, m, deterministic)
}
func (m *BindAccounQQReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindAccounQQReq.Merge(m, src)
}
func (m *BindAccounQQReq) XXX_Size() int {
	return xxx_messageInfo_BindAccounQQReq.Size(m)
}
func (m *BindAccounQQReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindAccounQQReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindAccounQQReq proto.InternalMessageInfo

func (m *BindAccounQQReq) GetAuthCode() string {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return ""
}

func (m *BindAccounQQReq) GetQq() string {
	if m != nil && m.Qq != nil {
		return *m.Qq
	}
	return ""
}

func (m *BindAccounQQReq) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

// 防沉迷身份认证请求
type AuthenticationReq struct {
	OpenId               *string  `protobuf:"bytes,1,opt,name=openId" json:"openId,omitempty"`
	Cardcode             *string  `protobuf:"bytes,2,opt,name=cardcode" json:"cardcode,omitempty"`
	Cardname             *string  `protobuf:"bytes,3,opt,name=cardname" json:"cardname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationReq) Reset()         { *m = AuthenticationReq{} }
func (m *AuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*AuthenticationReq) ProtoMessage()    {}
func (*AuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{36}
}

func (m *AuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationReq.Unmarshal(m, b)
}
func (m *AuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationReq.Marshal(b, m, deterministic)
}
func (m *AuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationReq.Merge(m, src)
}
func (m *AuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_AuthenticationReq.Size(m)
}
func (m *AuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationReq proto.InternalMessageInfo

func (m *AuthenticationReq) GetOpenId() string {
	if m != nil && m.OpenId != nil {
		return *m.OpenId
	}
	return ""
}

func (m *AuthenticationReq) GetCardcode() string {
	if m != nil && m.Cardcode != nil {
		return *m.Cardcode
	}
	return ""
}

func (m *AuthenticationReq) GetCardname() string {
	if m != nil && m.Cardname != nil {
		return *m.Cardname
	}
	return ""
}

func init() {
	proto.RegisterEnum("minGamePb.FcmState", FcmState_name, FcmState_value)
	proto.RegisterType((*WxLoginData)(nil), "minGamePb.WxLoginData")
	proto.RegisterType((*WanBaLoginData)(nil), "minGamePb.WanBaLoginData")
	proto.RegisterType((*ToutiaoLoginData)(nil), "minGamePb.ToutiaoLoginData")
	proto.RegisterType((*YiJieLoginData)(nil), "minGamePb.YiJieLoginData")
	proto.RegisterType((*YiJieDanJiLoginData)(nil), "minGamePb.YiJieDanJiLoginData")
	proto.RegisterType((*QQLoginData)(nil), "minGamePb.QQLoginData")
	proto.RegisterType((*BilibiliLoginData)(nil), "minGamePb.BilibiliLoginData")
	proto.RegisterType((*PasswordData)(nil), "minGamePb.PasswordData")
	proto.RegisterType((*OPPOLoginData)(nil), "minGamePb.OPPOLoginData")
	proto.RegisterType((*HuaweiLoginData)(nil), "minGamePb.HuaweiLoginData")
	proto.RegisterType((*BingChuanLoginData)(nil), "minGamePb.BingChuanLoginData")
	proto.RegisterType((*PhoneLoginData)(nil), "minGamePb.PhoneLoginData")
	proto.RegisterType((*BasicData)(nil), "minGamePb.BasicData")
	proto.RegisterType((*AuthReq)(nil), "minGamePb.AuthReq")
	proto.RegisterType((*FcmInfo)(nil), "minGamePb.FcmInfo")
	proto.RegisterType((*AuthRsp)(nil), "minGamePb.AuthRsp")
	proto.RegisterType((*VerifyReq)(nil), "minGamePb.VerifyReq")
	proto.RegisterType((*VerifyRsp)(nil), "minGamePb.VerifyRsp")
	proto.RegisterType((*AccountUser)(nil), "minGamePb.AccountUser")
	proto.RegisterType((*AccountGameInfoReq)(nil), "minGamePb.AccountGameInfoReq")
	proto.RegisterType((*AccountGameInfoRsp)(nil), "minGamePb.AccountGameInfoRsp")
	proto.RegisterType((*GetUserInfoReq)(nil), "minGamePb.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoRsp)(nil), "minGamePb.GetUserInfoRsp")
	proto.RegisterType((*SetPasswordReq)(nil), "minGamePb.SetPasswordReq")
	proto.RegisterType((*ModifyPasswordReq)(nil), "minGamePb.ModifyPasswordReq")
	proto.RegisterType((*GetPhoneCodeReq)(nil), "minGamePb.GetPhoneCodeReq")
	proto.RegisterType((*GetPhoneCodeRsp)(nil), "minGamePb.GetPhoneCodeRsp")
	proto.RegisterType((*WechatUnbindReq)(nil), "minGamePb.WechatUnbindReq")
	proto.RegisterType((*SetAccounfoReq)(nil), "minGamePb.SetAccounfoReq")
	proto.RegisterType((*BindAccounPlatformReq)(nil), "minGamePb.bindAccounPlatformReq")
	proto.RegisterType((*BindAccounWxPlatformReq)(nil), "minGamePb.bindAccounWxPlatformReq")
	proto.RegisterType((*QQBindLoginData)(nil), "minGamePb.QQBindLoginData")
	proto.RegisterType((*XCLoginData)(nil), "minGamePb.XCLoginData")
	proto.RegisterType((*GetBindQQReq)(nil), "minGamePb.GetBindQQReq")
	proto.RegisterType((*GetBindQQRsp)(nil), "minGamePb.GetBindQQRsp")
	proto.RegisterType((*BindAccounQQReq)(nil), "minGamePb.BindAccounQQReq")
	proto.RegisterType((*AuthenticationReq)(nil), "minGamePb.AuthenticationReq")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 1574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0xee, 0xfc, 0x77, 0x9c, 0x38, 0xc9, 0xb6, 0xb4, 0x47, 0x28, 0x51, 0x74, 0x6a, 0xa5,
	0xb4, 0x40, 0x24, 0xa2, 0x22, 0x24, 0xfe, 0x48, 0x34, 0x89, 0x12, 0x5a, 0x51, 0x1a, 0x5f, 0x1b,
	0xc2, 0x9f, 0x07, 0xb4, 0x3e, 0x6f, 0xec, 0x25, 0xf6, 0xde, 0xe5, 0xee, 0xec, 0xc4, 0x0f, 0x3c,
	0xc2, 0x2b, 0x12, 0x7c, 0x03, 0x04, 0xaf, 0x88, 0x37, 0x24, 0xf8, 0x00, 0x3c, 0x20, 0xf1, 0x2d,
	0xf8, 0x1e, 0x68, 0xe7, 0x76, 0x7d, 0x7b, 0x76, 0x49, 0x13, 0x28, 0x52, 0x79, 0x9b, 0x99, 0x9d,
	0xb9, 0xf9, 0xcd, 0xec, 0xec, 0xcc, 0xd8, 0x30, 0x4f, 0x83, 0x20, 0x1c, 0x8a, 0x74, 0x3d, 0x8a,
	0xc3, 0x34, 0x24, 0xf5, 0x01, 0x17, 0xbb, 0x74, 0xc0, 0xf6, 0xda, 0xcb, 0x73, 0x41, 0x38, 0x18,
	0x84, 0x22, 0x3b, 0xf0, 0xfe, 0xb4, 0xa0, 0x71, 0x70, 0xfa, 0x7e, 0xd8, 0xe5, 0x62, 0x9b, 0xa6,
	0x94, 0x10, 0x28, 0x05, 0x61, 0x87, 0xb9, 0xd6, 0xaa, 0xb5, 0x56, 0xf7, 0x91, 0x26, 0xd7, 0x61,
	0x9e, 0x89, 0x20, 0x1e, 0x47, 0x29, 0xeb, 0x74, 0x68, 0x4a, 0x5d, 0x1b, 0x0f, 0x8b, 0x42, 0xd2,
	0x04, 0x9b, 0x8f, 0x5c, 0x07, 0x8f, 0x6c, 0x3e, 0x22, 0x1e, 0xcc, 0x0d, 0x28, 0x17, 0x51, 0x9f,
	0xa6, 0x87, 0x61, 0x3c, 0x70, 0x4b, 0x78, 0x52, 0x90, 0x49, 0x9d, 0x64, 0xd8, 0x96, 0x2c, 0x43,
	0x9d, 0x72, 0xa6, 0x63, 0xca, 0x88, 0x0b, 0x55, 0x2e, 0x46, 0x3c, 0x65, 0xb1, 0x5b, 0x59, 0xb5,
	0xd6, 0x1c, 0x5f, 0xb3, 0x12, 0x2b, 0xed, 0x74, 0x62, 0xb7, 0x9a, 0x61, 0x95, 0x34, 0xb9, 0x02,
	0x95, 0x30, 0x62, 0x82, 0x77, 0xdc, 0x1a, 0x4a, 0x15, 0xe7, 0xfd, 0x62, 0x41, 0xf3, 0x80, 0x8a,
	0x4d, 0x9a, 0x87, 0x9a, 0xab, 0x5a, 0xa6, 0xaa, 0x74, 0x28, 0xa9, 0x23, 0x36, 0x56, 0x81, 0x6a,
	0x96, 0x2c, 0x43, 0x6d, 0x12, 0x4e, 0x16, 0x68, 0xcd, 0x0c, 0xe5, 0xa9, 0x84, 0xab, 0x83, 0xaa,
	0xe4, 0x41, 0x79, 0xbf, 0x5b, 0xb0, 0xf8, 0x28, 0x1c, 0xa6, 0x9c, 0x86, 0xcf, 0xf2, 0x4d, 0xdd,
	0x80, 0x26, 0x15, 0xa1, 0x18, 0x0f, 0xc2, 0x61, 0xf2, 0x19, 0x62, 0xcb, 0x82, 0x98, 0x9f, 0x48,
	0xb7, 0xc2, 0x0e, 0xf3, 0xbe, 0xb3, 0xa0, 0xf9, 0x31, 0xbf, 0xc7, 0x59, 0x1e, 0xcb, 0x22, 0x38,
	0x49, 0xe7, 0x48, 0x85, 0x22, 0x49, 0x29, 0xa1, 0x51, 0xa4, 0xf0, 0x4b, 0x52, 0x4a, 0x86, 0x5c,
	0x28, 0xd8, 0x92, 0x94, 0x19, 0x48, 0x58, 0x92, 0x28, 0xbc, 0x48, 0xcf, 0xc4, 0x52, 0x3e, 0x47,
	0x2c, 0x95, 0xd9, 0x58, 0xbc, 0x6f, 0x2d, 0xb8, 0x84, 0x20, 0xb7, 0xa9, 0xb8, 0xc7, 0x73, 0xa4,
	0xcb, 0x50, 0xeb, 0xb0, 0x11, 0x0f, 0xd8, 0x5d, 0x5d, 0x36, 0x13, 0xfe, 0xbf, 0xaf, 0x78, 0xef,
	0x67, 0x0b, 0x1a, 0xad, 0xd6, 0xb3, 0x5c, 0x03, 0xf9, 0xa3, 0xaa, 0x14, 0xde, 0xdf, 0x0f, 0x16,
	0x2c, 0x6d, 0xf2, 0x3e, 0x6f, 0xf3, 0x3e, 0x7f, 0x86, 0xf1, 0x7b, 0x9b, 0x30, 0xb7, 0x47, 0x93,
	0xe4, 0x24, 0x8c, 0x3b, 0xba, 0x49, 0x0c, 0x13, 0x16, 0xe7, 0x4d, 0x22, 0xe3, 0xb0, 0x15, 0x28,
	0x3d, 0x05, 0x70, 0xc2, 0x7b, 0x5f, 0x5a, 0x30, 0xff, 0x60, 0x6f, 0xef, 0xc1, 0xd9, 0x71, 0xba,
	0x50, 0x8d, 0x8e, 0xba, 0x1f, 0xd0, 0x01, 0xd3, 0x6d, 0x46, 0xb1, 0x33, 0xb1, 0x38, 0xe7, 0x88,
	0xa5, 0xf4, 0x98, 0x58, 0x7e, 0xb3, 0x60, 0xe1, 0xbd, 0x21, 0x3d, 0x61, 0x46, 0xc6, 0x9b, 0x60,
	0xa7, 0x89, 0xc2, 0x61, 0xa7, 0x89, 0x6a, 0x69, 0x63, 0x8c, 0xd0, 0x9e, 0xb4, 0x34, 0xe4, 0xc9,
	0x2a, 0x34, 0x32, 0xba, 0xcf, 0x46, 0xac, 0xaf, 0x60, 0x98, 0x22, 0xb2, 0x02, 0x90, 0xb1, 0x09,
	0xef, 0x0a, 0x85, 0xc1, 0x90, 0x3c, 0xb5, 0xd7, 0x38, 0x02, 0xb2, 0xc9, 0x45, 0x77, 0xab, 0x37,
	0xa4, 0x22, 0x8f, 0xc5, 0x85, 0xaa, 0x7c, 0xf3, 0x3c, 0x14, 0x2a, 0x20, 0xcd, 0xce, 0xf8, 0xb5,
	0xcf, 0xe1, 0xd7, 0x79, 0x8c, 0xdf, 0x0e, 0x34, 0xf7, 0x7a, 0xa1, 0x60, 0x05, 0x9f, 0x91, 0x94,
	0x88, 0x50, 0xfb, 0x54, 0x2c, 0xb9, 0x06, 0x75, 0x24, 0xf1, 0xa2, 0x33, 0x87, 0xb9, 0xa0, 0x50,
	0x2f, 0xce, 0x54, 0xbd, 0xbc, 0x0c, 0xf5, 0x4d, 0x9a, 0xf0, 0x00, 0x1d, 0xac, 0x00, 0x24, 0xc3,
	0xf6, 0x56, 0x8f, 0x0a, 0xc1, 0xfa, 0xca, 0x87, 0x21, 0xf1, 0xfe, 0xa8, 0x42, 0xf5, 0xce, 0x30,
	0xed, 0xf9, 0xec, 0x98, 0xdc, 0x84, 0x4a, 0x97, 0x0e, 0x74, 0x2b, 0x6a, 0x6e, 0x2c, 0xad, 0x4f,
	0xc6, 0xfc, 0xfa, 0x2e, 0x1e, 0xf8, 0x4a, 0x81, 0xac, 0x43, 0xe5, 0xe4, 0x74, 0x5b, 0x3f, 0xa7,
	0xc6, 0xc6, 0x15, 0x43, 0xd5, 0x98, 0xff, 0xbe, 0xd2, 0x22, 0x6f, 0x40, 0xfd, 0x84, 0x8a, 0x36,
	0x45, 0x13, 0x07, 0x4d, 0x5e, 0x30, 0x4d, 0x0a, 0xa3, 0xd4, 0xcf, 0x75, 0xc9, 0x3b, 0xd0, 0x48,
	0xb3, 0x51, 0x85, 0xa6, 0x25, 0x34, 0x7d, 0xd1, 0x30, 0x9d, 0x1e, 0x64, 0xbe, 0xa9, 0x2f, 0x5f,
	0x8a, 0xe0, 0xc1, 0x91, 0xaa, 0x14, 0xa4, 0x71, 0x3a, 0xb0, 0x53, 0x2c, 0x8c, 0xb2, 0x2f, 0x49,
	0x99, 0x6b, 0x3a, 0xa2, 0x29, 0x8d, 0xf7, 0xe3, 0xbe, 0x1a, 0xff, 0xb9, 0x80, 0xbc, 0x0e, 0xb5,
	0x31, 0xff, 0x9c, 0xa3, 0xff, 0xda, 0x0c, 0xf4, 0xe2, 0xe8, 0xf1, 0x27, 0xaa, 0x32, 0x45, 0xad,
	0x16, 0x1a, 0xd5, 0x67, 0x52, 0x64, 0x34, 0x5d, 0x5f, 0x69, 0x91, 0xdb, 0x50, 0x69, 0xb7, 0x51,
	0x1f, 0x50, 0xff, 0x9a, 0xa1, 0x3f, 0xd3, 0xea, 0x7c, 0xa5, 0x4b, 0x76, 0xa0, 0x29, 0x3d, 0xb2,
	0x0e, 0x15, 0x0a, 0x62, 0x03, 0xad, 0x57, 0xa6, 0x21, 0x16, 0x07, 0x8f, 0x3f, 0x65, 0x45, 0x6e,
	0x43, 0x2d, 0x8c, 0xa2, 0x2c, 0xc9, 0x73, 0xf8, 0x05, 0xd7, 0xf8, 0x42, 0xa1, 0xfd, 0xf8, 0x13,
	0x4d, 0xf2, 0x16, 0xcc, 0x45, 0x46, 0x7b, 0x73, 0xe7, 0xd1, 0xf2, 0xaa, 0x61, 0x69, 0x76, 0x3f,
	0xbf, 0xa0, 0x2c, 0x6b, 0x02, 0x0b, 0x1a, 0x2d, 0x9b, 0x33, 0x89, 0x2d, 0xbe, 0x14, 0x3f, 0xd7,
	0x25, 0x1b, 0x50, 0x6f, 0xeb, 0x02, 0x77, 0x17, 0xd0, 0xf0, 0xb2, 0x99, 0x2c, 0x7d, 0xe6, 0xe7,
	0x6a, 0xe4, 0x4d, 0x80, 0x1e, 0xf6, 0x2e, 0x34, 0x5a, 0x44, 0xa3, 0x65, 0xc3, 0x68, 0xaa, 0xb1,
	0xf9, 0x86, 0x36, 0xd9, 0x82, 0xf9, 0x36, 0x17, 0xdd, 0x40, 0xb6, 0x0b, 0x34, 0x5f, 0x42, 0xf3,
	0x97, 0x0a, 0x17, 0x34, 0xdd, 0x4e, 0xfc, 0xa2, 0x8d, 0x04, 0xd0, 0x6a, 0x6d, 0x72, 0x91, 0x25,
	0x8a, 0xcc, 0x00, 0xc8, 0x0e, 0x0d, 0x00, 0xb9, 0x36, 0xb9, 0x05, 0xa5, 0xd3, 0xe0, 0xa4, 0xef,
	0x5e, 0x9a, 0x29, 0xa4, 0x8f, 0xb6, 0x72, 0x0b, 0xd4, 0xf1, 0xda, 0x50, 0xdd, 0x09, 0x06, 0x77,
	0xc5, 0x61, 0x48, 0x6e, 0x42, 0x39, 0x49, 0x69, 0xca, 0xd4, 0x73, 0xbe, 0x64, 0xd8, 0xed, 0x04,
	0x83, 0x87, 0xf2, 0xc8, 0xcf, 0x34, 0xc8, 0x2b, 0xb0, 0xc4, 0xc4, 0x61, 0x18, 0x07, 0x32, 0xe3,
	0xe1, 0x30, 0x7d, 0xc4, 0xd5, 0x1c, 0x71, 0xfc, 0xd9, 0x03, 0xef, 0x6b, 0x4b, 0x35, 0x8d, 0x24,
	0x7a, 0xec, 0x2c, 0xca, 0xa7, 0xb6, 0x3d, 0xbd, 0x0a, 0xab, 0xdf, 0x11, 0xd8, 0x03, 0xe6, 0x7c,
	0xcd, 0xca, 0x93, 0x1e, 0x4d, 0x64, 0xc0, 0xf8, 0xc4, 0x6b, 0xbe, 0x66, 0xc9, 0x75, 0x70, 0x0e,
	0x83, 0xac, 0xd5, 0x37, 0x36, 0x48, 0x31, 0x04, 0x19, 0xa5, 0x2f, 0x8f, 0xbd, 0xaf, 0x2c, 0xa8,
	0x7f, 0xc8, 0x62, 0x7e, 0x38, 0x96, 0x8d, 0xec, 0x1a, 0xd4, 0x83, 0x1e, 0x0b, 0x8e, 0xb6, 0x72,
	0x60, 0xb9, 0x40, 0xa2, 0x4b, 0x58, 0x3c, 0x62, 0xb1, 0x46, 0x97, 0x71, 0x46, 0xfb, 0x73, 0x9e,
	0xd4, 0xfe, 0x5c, 0xa8, 0x8e, 0xe4, 0x4c, 0x0a, 0xf5, 0x94, 0xd2, 0xac, 0x77, 0x63, 0x82, 0x23,
	0x89, 0xcc, 0x78, 0xad, 0x42, 0xbc, 0xde, 0x4f, 0x16, 0x34, 0xee, 0x64, 0xf4, 0x7e, 0xc2, 0x62,
	0x03, 0x93, 0xf5, 0x37, 0x98, 0xec, 0x0b, 0x60, 0x72, 0x0a, 0x98, 0xe4, 0x0c, 0x08, 0x62, 0x46,
	0x53, 0x86, 0xb7, 0x5a, 0xc2, 0x5b, 0x35, 0x24, 0x72, 0x45, 0xea, 0xd3, 0x24, 0xc5, 0x4a, 0x42,
	0x95, 0x32, 0xaa, 0x14, 0x85, 0xde, 0x10, 0x88, 0x42, 0x8c, 0x8e, 0x65, 0xea, 0xb3, 0x54, 0xab,
	0x98, 0xd4, 0xd8, 0x70, 0xfc, 0x5c, 0x70, 0x11, 0xf8, 0x79, 0x06, 0x1c, 0x33, 0x03, 0xde, 0xbb,
	0xb3, 0x6e, 0x93, 0x48, 0xbe, 0x08, 0xb9, 0x39, 0xb9, 0xd6, 0xaa, 0x33, 0xf5, 0x22, 0x8c, 0xac,
	0xfa, 0xa8, 0xe3, 0xad, 0x41, 0x73, 0x97, 0xa1, 0x40, 0x83, 0x56, 0x5b, 0xd8, 0x04, 0xb1, 0xe2,
	0xbc, 0xb7, 0x8b, 0x9a, 0x05, 0x3f, 0xd6, 0x13, 0xfd, 0x6c, 0x43, 0xf3, 0x21, 0x4b, 0x75, 0xc3,
	0x9b, 0xf5, 0x53, 0xd7, 0x7e, 0xce, 0xdc, 0xf6, 0xbe, 0xb1, 0x60, 0xe9, 0x7e, 0xd8, 0xe1, 0x87,
	0x63, 0xf3, 0x4b, 0x17, 0x18, 0xcd, 0xc6, 0x4a, 0x61, 0x9f, 0xb1, 0x52, 0x38, 0x67, 0xad, 0x14,
	0xa5, 0x29, 0x50, 0x9f, 0xc2, 0xc2, 0x2e, 0x4b, 0xb1, 0x23, 0xcb, 0x27, 0x24, 0x11, 0x15, 0x36,
	0x17, 0xdb, 0x74, 0xb3, 0x0c, 0x35, 0x09, 0x45, 0x64, 0xab, 0xa8, 0x3c, 0x9a, 0xf0, 0xb2, 0x5b,
	0xa4, 0xe3, 0x48, 0x7a, 0xb7, 0xd7, 0xca, 0x3e, 0xd2, 0xde, 0x6b, 0x53, 0x1f, 0x4f, 0x22, 0x59,
	0xb1, 0x31, 0x93, 0xeb, 0x55, 0x2a, 0xcb, 0xd1, 0x42, 0x65, 0x43, 0xe2, 0x7d, 0x02, 0x0b, 0x07,
	0x2c, 0xe8, 0xd1, 0x74, 0x5f, 0xb4, 0xb9, 0xb8, 0x68, 0x86, 0x0a, 0x35, 0x6b, 0xe3, 0xc7, 0x73,
	0x81, 0x77, 0x88, 0xd7, 0x98, 0x5d, 0xef, 0x79, 0x6a, 0x7c, 0x19, 0x6a, 0x01, 0x8d, 0x3b, 0xc6,
	0x9e, 0x36, 0xe1, 0xf5, 0x19, 0xa6, 0xc2, 0xc9, 0xcf, 0x24, 0xef, 0xfd, 0x68, 0xc1, 0xf3, 0x12,
	0x7c, 0xe6, 0x69, 0x4f, 0xed, 0x91, 0xd2, 0x9f, 0x4e, 0x92, 0x85, 0x1b, 0x0a, 0xd2, 0xf2, 0x4b,
	0x74, 0x98, 0xf6, 0xb6, 0x0c, 0x2f, 0x9a, 0x9f, 0x1a, 0x2d, 0xce, 0x85, 0x46, 0x4b, 0x9e, 0xb6,
	0xd2, 0x13, 0xd2, 0xe6, 0x7d, 0x6f, 0xc1, 0xd5, 0x1c, 0xf0, 0xc1, 0xe9, 0xbf, 0x81, 0x9c, 0xef,
	0x8f, 0xce, 0xb9, 0xf6, 0xc7, 0x0b, 0xc0, 0xfc, 0xd5, 0x82, 0x85, 0xa9, 0x88, 0xff, 0x47, 0x3f,
	0x6c, 0xbf, 0x80, 0x86, 0x31, 0xd3, 0xc9, 0x65, 0x28, 0xa7, 0xe1, 0x11, 0xd3, 0xbf, 0x48, 0x32,
	0x26, 0xfb, 0xef, 0x42, 0xb7, 0x0e, 0x49, 0x3e, 0xb5, 0xdf, 0x78, 0x1e, 0xcc, 0xed, 0xb2, 0x54,
	0x26, 0xaf, 0xd5, 0x52, 0xf7, 0x3a, 0x9d, 0x38, 0x6f, 0xc5, 0xd4, 0x49, 0x22, 0x99, 0xa2, 0xe3,
	0x63, 0xfd, 0x1b, 0xf0, 0xf8, 0xd8, 0xdb, 0x87, 0x85, 0xcd, 0x49, 0x99, 0x64, 0x9f, 0x31, 0x4b,
	0xc1, 0x9a, 0x2a, 0x85, 0xcc, 0xdc, 0xd6, 0xe6, 0x32, 0x33, 0xc6, 0x18, 0x2e, 0x4f, 0xee, 0x35,
	0x80, 0x25, 0xb9, 0x73, 0x30, 0x91, 0xf2, 0x80, 0xa6, 0x3c, 0x14, 0xaa, 0xc3, 0xca, 0xc4, 0xdd,
	0x2d, 0xfc, 0xe9, 0xf6, 0xcf, 0x1f, 0xe5, 0xad, 0x57, 0xa1, 0xa6, 0x57, 0x23, 0xd2, 0x80, 0xea,
	0xc3, 0x61, 0x10, 0xb0, 0x24, 0x59, 0x7c, 0x8e, 0xd4, 0xa0, 0xb4, 0x43, 0x79, 0x7f, 0xd1, 0x22,
	0x00, 0x95, 0xfb, 0xa1, 0xa0, 0x5d, 0xb6, 0x68, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x99,
	0xd0, 0xfc, 0x17, 0x15, 0x00, 0x00,
}
