// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: message_code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageCode int32

const (
	// -- test --
	MessageCode_OpTest MessageCode = 0
	// -- Business : 1-500 --
	MessageCode_OPUpdateProps  MessageCode = 1 //更新道具
	MessageCode_OPUpdateLevel  MessageCode = 2 //更新等级
	MessageCode_OPShowRedot    MessageCode = 3 //显示红点
	MessageCode_OPPing         MessageCode = 4 //Ping 消息 收到ping 消息后需要立即返回Pong消息
	MessageCode_OPPong         MessageCode = 5 //Pong 消息
	MessageCode_OPUpdateClient MessageCode = 6 //客户端更新
	// -- Push : 501-700 --
	MessageCode_OPSubscribe      MessageCode = 501 //订阅消息
	MessageCode_OPUnsubscribe    MessageCode = 502 //取消订阅消息
	MessageCode_OPFriendChat     MessageCode = 503 //好友聊天
	MessageCode_OPWorldChat      MessageCode = 504 //世界聊天
	MessageCode_OPAnnounce       MessageCode = 505 //公告
	MessageCode_OPApplyFriend    MessageCode = 506 //好友申请
	MessageCode_OPBroadCast      MessageCode = 507 //广播
	MessageCode_OPKickBlackList  MessageCode = 508 //踢掉黑名单玩家
	MessageCode_OPKickSealPlayer MessageCode = 509 //踢掉封号玩家
	MessageCode_OPRecharge       MessageCode = 510 //支付未到账
)

// Enum value maps for MessageCode.
var (
	MessageCode_name = map[int32]string{
		0:   "OpTest",
		1:   "OPUpdateProps",
		2:   "OPUpdateLevel",
		3:   "OPShowRedot",
		4:   "OPPing",
		5:   "OPPong",
		6:   "OPUpdateClient",
		501: "OPSubscribe",
		502: "OPUnsubscribe",
		503: "OPFriendChat",
		504: "OPWorldChat",
		505: "OPAnnounce",
		506: "OPApplyFriend",
		507: "OPBroadCast",
		508: "OPKickBlackList",
		509: "OPKickSealPlayer",
		510: "OPRecharge",
	}
	MessageCode_value = map[string]int32{
		"OpTest":           0,
		"OPUpdateProps":    1,
		"OPUpdateLevel":    2,
		"OPShowRedot":      3,
		"OPPing":           4,
		"OPPong":           5,
		"OPUpdateClient":   6,
		"OPSubscribe":      501,
		"OPUnsubscribe":    502,
		"OPFriendChat":     503,
		"OPWorldChat":      504,
		"OPAnnounce":       505,
		"OPApplyFriend":    506,
		"OPBroadCast":      507,
		"OPKickBlackList":  508,
		"OPKickSealPlayer": 509,
		"OPRecharge":       510,
	}
)

func (x MessageCode) Enum() *MessageCode {
	p := new(MessageCode)
	*p = x
	return p
}

func (x MessageCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageCode) Descriptor() protoreflect.EnumDescriptor {
	return file_message_code_proto_enumTypes[0].Descriptor()
}

func (MessageCode) Type() protoreflect.EnumType {
	return &file_message_code_proto_enumTypes[0]
}

func (x MessageCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageCode(num)
	return nil
}

// Deprecated: Use MessageCode.Descriptor instead.
func (MessageCode) EnumDescriptor() ([]byte, []int) {
	return file_message_code_proto_rawDescGZIP(), []int{0}
}

var File_message_code_proto protoreflect.FileDescriptor

var file_message_code_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xbc, 0x02, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x70, 0x54, 0x65, 0x73, 0x74, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x73, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x53, 0x68, 0x6f, 0x77,
	0x52, 0x65, 0x64, 0x6f, 0x74, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x50, 0x69, 0x6e,
	0x67, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x50, 0x6f, 0x6e, 0x67, 0x10, 0x05, 0x12,
	0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0b, 0x4f, 0x50, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x10, 0xf5, 0x03, 0x12, 0x12, 0x0a, 0x0d, 0x4f, 0x50, 0x55, 0x6e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x10, 0xf6, 0x03, 0x12, 0x11, 0x0a, 0x0c, 0x4f, 0x50, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x74, 0x10, 0xf7, 0x03, 0x12, 0x10, 0x0a, 0x0b,
	0x4f, 0x50, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x74, 0x10, 0xf8, 0x03, 0x12, 0x0f,
	0x0a, 0x0a, 0x4f, 0x50, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x10, 0xf9, 0x03, 0x12,
	0x12, 0x0a, 0x0d, 0x4f, 0x50, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x10, 0xfa, 0x03, 0x12, 0x10, 0x0a, 0x0b, 0x4f, 0x50, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x73, 0x74, 0x10, 0xfb, 0x03, 0x12, 0x14, 0x0a, 0x0f, 0x4f, 0x50, 0x4b, 0x69, 0x63, 0x6b, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x10, 0xfc, 0x03, 0x12, 0x15, 0x0a, 0x10, 0x4f,
	0x50, 0x4b, 0x69, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10,
	0xfd, 0x03, 0x12, 0x0f, 0x0a, 0x0a, 0x4f, 0x50, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x10, 0xfe, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_message_code_proto_rawDescOnce sync.Once
	file_message_code_proto_rawDescData = file_message_code_proto_rawDesc
)

func file_message_code_proto_rawDescGZIP() []byte {
	file_message_code_proto_rawDescOnce.Do(func() {
		file_message_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_code_proto_rawDescData)
	})
	return file_message_code_proto_rawDescData
}

var file_message_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_code_proto_goTypes = []interface{}{
	(MessageCode)(0), // 0: MessageCode
}
var file_message_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_code_proto_init() }
func file_message_code_proto_init() {
	if File_message_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_code_proto_goTypes,
		DependencyIndexes: file_message_code_proto_depIdxs,
		EnumInfos:         file_message_code_proto_enumTypes,
	}.Build()
	File_message_code_proto = out.File
	file_message_code_proto_rawDesc = nil
	file_message_code_proto_goTypes = nil
	file_message_code_proto_depIdxs = nil
}
