// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phone.proto

package minGamePb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 绑定手机号请求
type BindPhoneReq struct {
	Playerid             *string  `protobuf:"bytes,1,req,name=playerid" json:"playerid,omitempty"`
	Phoneno              *string  `protobuf:"bytes,2,req,name=phoneno" json:"phoneno,omitempty"`
	Code                 *string  `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindPhoneReq) Reset()         { *m = BindPhoneReq{} }
func (m *BindPhoneReq) String() string { return proto.CompactTextString(m) }
func (*BindPhoneReq) ProtoMessage()    {}
func (*BindPhoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{0}
}

func (m *BindPhoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindPhoneReq.Unmarshal(m, b)
}
func (m *BindPhoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindPhoneReq.Marshal(b, m, deterministic)
}
func (m *BindPhoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindPhoneReq.Merge(m, src)
}
func (m *BindPhoneReq) XXX_Size() int {
	return xxx_messageInfo_BindPhoneReq.Size(m)
}
func (m *BindPhoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindPhoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindPhoneReq proto.InternalMessageInfo

func (m *BindPhoneReq) GetPlayerid() string {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return ""
}

func (m *BindPhoneReq) GetPhoneno() string {
	if m != nil && m.Phoneno != nil {
		return *m.Phoneno
	}
	return ""
}

func (m *BindPhoneReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

// 绑定手机号响应
type BindPhoneRsp struct {
	Result               *int32   `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindPhoneRsp) Reset()         { *m = BindPhoneRsp{} }
func (m *BindPhoneRsp) String() string { return proto.CompactTextString(m) }
func (*BindPhoneRsp) ProtoMessage()    {}
func (*BindPhoneRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{1}
}

func (m *BindPhoneRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindPhoneRsp.Unmarshal(m, b)
}
func (m *BindPhoneRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindPhoneRsp.Marshal(b, m, deterministic)
}
func (m *BindPhoneRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindPhoneRsp.Merge(m, src)
}
func (m *BindPhoneRsp) XXX_Size() int {
	return xxx_messageInfo_BindPhoneRsp.Size(m)
}
func (m *BindPhoneRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindPhoneRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BindPhoneRsp proto.InternalMessageInfo

func (m *BindPhoneRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *BindPhoneRsp) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

// 修改手机号请求
type ModifyBindPhoneReq struct {
	Playerid             *string  `protobuf:"bytes,1,req,name=playerid" json:"playerid,omitempty"`
	Oldphone             *string  `protobuf:"bytes,2,req,name=oldphone" json:"oldphone,omitempty"`
	Oldcode              *string  `protobuf:"bytes,3,req,name=oldcode" json:"oldcode,omitempty"`
	Newphone             *string  `protobuf:"bytes,4,req,name=newphone" json:"newphone,omitempty"`
	Newcode              *string  `protobuf:"bytes,5,req,name=newcode" json:"newcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBindPhoneReq) Reset()         { *m = ModifyBindPhoneReq{} }
func (m *ModifyBindPhoneReq) String() string { return proto.CompactTextString(m) }
func (*ModifyBindPhoneReq) ProtoMessage()    {}
func (*ModifyBindPhoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{2}
}

func (m *ModifyBindPhoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBindPhoneReq.Unmarshal(m, b)
}
func (m *ModifyBindPhoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBindPhoneReq.Marshal(b, m, deterministic)
}
func (m *ModifyBindPhoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBindPhoneReq.Merge(m, src)
}
func (m *ModifyBindPhoneReq) XXX_Size() int {
	return xxx_messageInfo_ModifyBindPhoneReq.Size(m)
}
func (m *ModifyBindPhoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBindPhoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBindPhoneReq proto.InternalMessageInfo

func (m *ModifyBindPhoneReq) GetPlayerid() string {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return ""
}

func (m *ModifyBindPhoneReq) GetOldphone() string {
	if m != nil && m.Oldphone != nil {
		return *m.Oldphone
	}
	return ""
}

func (m *ModifyBindPhoneReq) GetOldcode() string {
	if m != nil && m.Oldcode != nil {
		return *m.Oldcode
	}
	return ""
}

func (m *ModifyBindPhoneReq) GetNewphone() string {
	if m != nil && m.Newphone != nil {
		return *m.Newphone
	}
	return ""
}

func (m *ModifyBindPhoneReq) GetNewcode() string {
	if m != nil && m.Newcode != nil {
		return *m.Newcode
	}
	return ""
}

// 修改手机号响应
type ModifyBindPhoneRsp struct {
	Result               *int32   `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	ErrMsg               *string  `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBindPhoneRsp) Reset()         { *m = ModifyBindPhoneRsp{} }
func (m *ModifyBindPhoneRsp) String() string { return proto.CompactTextString(m) }
func (*ModifyBindPhoneRsp) ProtoMessage()    {}
func (*ModifyBindPhoneRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{3}
}

func (m *ModifyBindPhoneRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBindPhoneRsp.Unmarshal(m, b)
}
func (m *ModifyBindPhoneRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBindPhoneRsp.Marshal(b, m, deterministic)
}
func (m *ModifyBindPhoneRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBindPhoneRsp.Merge(m, src)
}
func (m *ModifyBindPhoneRsp) XXX_Size() int {
	return xxx_messageInfo_ModifyBindPhoneRsp.Size(m)
}
func (m *ModifyBindPhoneRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBindPhoneRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBindPhoneRsp proto.InternalMessageInfo

func (m *ModifyBindPhoneRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *ModifyBindPhoneRsp) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

// 获取手机验证码请求(path:/phone/sendcode)
type PhoneSendCodeReq struct {
	Playerid             *string  `protobuf:"bytes,1,req,name=playerid" json:"playerid,omitempty"`
	Phoneno              *string  `protobuf:"bytes,2,req,name=phoneno" json:"phoneno,omitempty"`
	Gamename             *string  `protobuf:"bytes,3,req,name=gamename" json:"gamename,omitempty"`
	Second               *int32   `protobuf:"varint,4,req,name=second" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneSendCodeReq) Reset()         { *m = PhoneSendCodeReq{} }
func (m *PhoneSendCodeReq) String() string { return proto.CompactTextString(m) }
func (*PhoneSendCodeReq) ProtoMessage()    {}
func (*PhoneSendCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{4}
}

func (m *PhoneSendCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneSendCodeReq.Unmarshal(m, b)
}
func (m *PhoneSendCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneSendCodeReq.Marshal(b, m, deterministic)
}
func (m *PhoneSendCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneSendCodeReq.Merge(m, src)
}
func (m *PhoneSendCodeReq) XXX_Size() int {
	return xxx_messageInfo_PhoneSendCodeReq.Size(m)
}
func (m *PhoneSendCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneSendCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneSendCodeReq proto.InternalMessageInfo

func (m *PhoneSendCodeReq) GetPlayerid() string {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return ""
}

func (m *PhoneSendCodeReq) GetPhoneno() string {
	if m != nil && m.Phoneno != nil {
		return *m.Phoneno
	}
	return ""
}

func (m *PhoneSendCodeReq) GetGamename() string {
	if m != nil && m.Gamename != nil {
		return *m.Gamename
	}
	return ""
}

func (m *PhoneSendCodeReq) GetSecond() int32 {
	if m != nil && m.Second != nil {
		return *m.Second
	}
	return 0
}

// 获取验证码响应(path:/phone/sendcode)
type PhoneSendCodeRsp struct {
	Phonecode            *string  `protobuf:"bytes,1,req,name=phonecode" json:"phonecode,omitempty"`
	Remaintime           *int32   `protobuf:"varint,2,req,name=remaintime" json:"remaintime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneSendCodeRsp) Reset()         { *m = PhoneSendCodeRsp{} }
func (m *PhoneSendCodeRsp) String() string { return proto.CompactTextString(m) }
func (*PhoneSendCodeRsp) ProtoMessage()    {}
func (*PhoneSendCodeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e585c54dbe5137, []int{5}
}

func (m *PhoneSendCodeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneSendCodeRsp.Unmarshal(m, b)
}
func (m *PhoneSendCodeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneSendCodeRsp.Marshal(b, m, deterministic)
}
func (m *PhoneSendCodeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneSendCodeRsp.Merge(m, src)
}
func (m *PhoneSendCodeRsp) XXX_Size() int {
	return xxx_messageInfo_PhoneSendCodeRsp.Size(m)
}
func (m *PhoneSendCodeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneSendCodeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneSendCodeRsp proto.InternalMessageInfo

func (m *PhoneSendCodeRsp) GetPhonecode() string {
	if m != nil && m.Phonecode != nil {
		return *m.Phonecode
	}
	return ""
}

func (m *PhoneSendCodeRsp) GetRemaintime() int32 {
	if m != nil && m.Remaintime != nil {
		return *m.Remaintime
	}
	return 0
}

func init() {
	proto.RegisterType((*BindPhoneReq)(nil), "minGamePb.BindPhoneReq")
	proto.RegisterType((*BindPhoneRsp)(nil), "minGamePb.BindPhoneRsp")
	proto.RegisterType((*ModifyBindPhoneReq)(nil), "minGamePb.ModifyBindPhoneReq")
	proto.RegisterType((*ModifyBindPhoneRsp)(nil), "minGamePb.ModifyBindPhoneRsp")
	proto.RegisterType((*PhoneSendCodeReq)(nil), "minGamePb.PhoneSendCodeReq")
	proto.RegisterType((*PhoneSendCodeRsp)(nil), "minGamePb.PhoneSendCodeRsp")
}

func init() { proto.RegisterFile("phone.proto", fileDescriptor_c0e585c54dbe5137) }

var fileDescriptor_c0e585c54dbe5137 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x69, 0x6d, 0xb4, 0x19, 0x2b, 0xc8, 0x1e, 0x24, 0x04, 0x91, 0x92, 0x53, 0x4f, 0x3e,
	0x82, 0x07, 0x15, 0x3c, 0x15, 0x4a, 0xbc, 0x78, 0x8d, 0xd9, 0xb1, 0x2e, 0x64, 0x67, 0xe2, 0x26,
	0xa5, 0x14, 0x7c, 0x14, 0x1f, 0x56, 0x76, 0x76, 0x1b, 0x8b, 0x5e, 0x44, 0x6f, 0xf9, 0x66, 0xf8,
	0x66, 0xfe, 0xc9, 0xc2, 0x69, 0xfb, 0xca, 0x84, 0xd7, 0xad, 0xe3, 0x9e, 0x55, 0x6a, 0x0d, 0x3d,
	0x54, 0x16, 0x57, 0xcf, 0xf9, 0xac, 0x66, 0x6b, 0x99, 0x42, 0x23, 0x3f, 0xab, 0xea, 0x9a, 0x37,
	0xd4, 0x07, 0x2c, 0x9e, 0x60, 0x76, 0x6b, 0x48, 0xaf, 0xbc, 0x5a, 0xe2, 0x9b, 0xca, 0x61, 0xda,
	0x36, 0xd5, 0x0e, 0x9d, 0xd1, 0xd9, 0x68, 0x3e, 0x5e, 0xa4, 0xe5, 0xc0, 0x2a, 0x83, 0x13, 0x59,
	0x41, 0x9c, 0x8d, 0xa5, 0xb5, 0x47, 0xa5, 0x60, 0x52, 0xb3, 0xc6, 0xec, 0x68, 0x3e, 0x5a, 0xa4,
	0xa5, 0x7c, 0x17, 0x37, 0x87, 0x93, 0xbb, 0x56, 0x5d, 0xc0, 0xb1, 0xc3, 0x6e, 0xd3, 0xf4, 0x32,
	0x37, 0x29, 0x23, 0xf9, 0x3a, 0x3a, 0xb7, 0xec, 0xd6, 0xd9, 0x58, 0xec, 0x48, 0xc5, 0xc7, 0x08,
	0xd4, 0x92, 0xb5, 0x79, 0xd9, 0xfd, 0x3a, 0x60, 0x0e, 0x53, 0x6e, 0xb4, 0x84, 0x8a, 0x09, 0x07,
	0xf6, 0xe1, 0xb9, 0xd1, 0x31, 0xa5, 0x84, 0x8f, 0xe8, 0x2d, 0xc2, 0x6d, 0xb0, 0x26, 0xc1, 0xda,
	0xb3, 0xb7, 0x08, 0xb7, 0x62, 0x25, 0xc1, 0x8a, 0x58, 0xdc, 0xff, 0x4c, 0xf7, 0x87, 0x23, 0xdf,
	0xe1, 0x5c, 0xdc, 0x47, 0x24, 0x7d, 0xc7, 0xfa, 0x1f, 0x4f, 0x90, 0xc3, 0x74, 0x5d, 0x59, 0xa4,
	0xca, 0xee, 0x0f, 0x1c, 0xd8, 0x6f, 0xef, 0xb0, 0x66, 0xd2, 0x72, 0x5f, 0x52, 0x46, 0x2a, 0x56,
	0xdf, 0xb7, 0x77, 0xad, 0xba, 0x84, 0x54, 0x46, 0xca, 0xcd, 0x61, 0xfd, 0x57, 0x41, 0x5d, 0x01,
	0x38, 0xb4, 0x95, 0xa1, 0xde, 0xd8, 0xf0, 0x8f, 0x93, 0xf2, 0xa0, 0xf2, 0x19, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x8f, 0xb4, 0x64, 0x84, 0x02, 0x00, 0x00,
}
